### ISSUE TITLE
交易品种只能显示600051，不能显示其它品种

### ISSUE THREAD

**Issue by beolee** [flameOnYou/mt4plus#3]
在anaconda2环境下，直接运行main.py，运行过程中出现以下问题：
2018-12-03 08:54:52,953 connectionpool.py[line:396] DEBUG http://quotes.money.16
3.com:80 "GET /service/chddata.html?code=0600051&start=20000101&end=20181203 HTT
P/1.1" 200 None
str(Exception): <type 'exceptions.Exception'>
str(e):         'module' object has no attribute '_strptime'
repr(e):        AttributeError("'module' object has no attribute '_strptime'",)
e.message:      'module' object has no attribute '_strptime'
traceback.print_exc():
Traceback (most recent call last):
  File "main.py", line 110, in getHistory
    d=datetime.datetime.strptime(dates,dataformate)
AttributeError: 'module' object has no attribute '_strptime'
traceback.format_exc():
Traceback (most recent call last):
  File "main.py", line 110, in getHistory
    d=datetime.datetime.strptime(dates,dataformate)
AttributeError: 'module' object has no attribute '_strptime'
执行完程序后，打开mt4软件，可以看到交易品种中只显示了一个品种600051，其它品种均不能显示。打开交易品种子窗口，可以看到mystock目录下，只有600051这个品种显示是激活状态，其它品种均为灰色。

email: 30944272@qq.com

**Comment by webbrain-one** [comment]
已提交 PR：https://github.com/flameOnYou/mt4plus/pull/4

该 PR 用于修复交易品种只显示 600051、其它品种无法激活的问题，主要修复了日期解析时触发 `_strptime` 相关异常导致数据加载不完整的情况。
